### ISSUE TITLE
Cool project! Got code?

### ISSUE THREAD

**Issue by 1ib3r7yr3igns** [chaintip/chaintip-reddit#1]
Also, chaintip.com is linking to github.com/chaintip/reddit_bot/issues instead of github.com/chaintip/reddit/issues.

**Comment by chaintip** [comment]
Thanks, that's fixed now. I also pointed it to the new issue page.

Code will come soon. I'd like to wait a bit until chaintip gains some traction so that someone doesn't fork the code right now and pick another name. Would you be interested in contributing?

I put the blank repo up so that users can start to log bugs.
